### ISSUE TITLE
登录界面

### ISSUE THREAD

**Issue by RcoIl** [1in9e/gosint#10]
在 docker-compose up -d --build 之后，直接访问 8001 端口一直显示 502？在哪跳转呢。

**Comment by gdft2112** [comment]
502的话你web的docker应该一直在重启，你看下

**Comment by RcoIl** [comment]
> 502你说你web的docker应该一直在重启，你看下

但是我使用的是默认配置，什么都没有修改。

**Comment by gdft2112** [comment]
我用我机子直接跑是没问题的，你可以等等，不然的话就重新来一遍，还是这样子就排查下，当然漏扫要等作者修好了才能用。。。单独跑和一起跑漏扫那个docker都会一直重启

**Comment by MarkKC** [comment]
我也是一直502

**Comment by 1in9e** [comment]
> 在 docker-compose up -d --build 之后，直接访问 8001 端口一直显示 502？在哪跳转呢。

第一次启动，需稍等片刻创建数据库启动rabbitmq/redis等，后续即可快速启动，感谢反馈～
