### ISSUE TITLE
500报错

### ISSUE THREAD

**Issue by arno567** [1in9e/gosint#11]
使用下列命令一键安装
cd gosint/
docker-compose up -d --build
登录--扫描管理--增加扫描任务--save（保存）后报错500
![image](https://user-images.githubusercontent.com/24539434/147623271-3f2898f8-f7c6-4f64-9f7a-78445ba225cf.png)

**Comment by Liang2580** [comment]
没有添加扫描名称

**Comment by 1in9e** [comment]
扫描名称、扫描引擎、资产为必填项，感谢反馈～
