### ISSUE TITLE
子域名扫描没反应

### ISSUE THREAD

**Issue by gdft2112** [1in9e/gosint#12]
子域名扫描不扫子域名只是扫了我加的域名

**Comment by wycdavid** [comment]
> 子域名扫描不扫子域名只是扫了我加的域名

我是正常的，应该是用xray的，需要license，readme中提到的

**Comment by gdft2112** [comment]
好

**Comment by 1in9e** [comment]
默认子域名扫描模块包含高级版xray, 需要添加xray license,可通过flower监控查看是哪里出了问题
