### ISSUE TITLE
本地开放环境：您还没有激活Simple Pro

### ISSUE THREAD

**Issue by austfish** [1in9e/gosint#18]
![image](https://user-images.githubusercontent.com/23695674/149274679-34407e39-51e8-478c-8a1a-9fdb696835d6.png)
目前这本地调试的话必须使用这个Simple Pro模板吗，可以替换Simple UI免费版本调试吗

**Comment by Miracles666** [comment]
解决了吗 我也这个问题

**Comment by 1in9e** [comment]
可以替换，修改Django setting即可；
本地调试，或可直接安装pro，方法见Dockerfile
