### ISSUE TITLE
扫描无结果

### ISSUE THREAD

**Issue by nu0l** [1in9e/gosint#19]
新建任务后，[漏洞任务]仅文件指纹有结果，
版本是：1.0.2，
配置如下（更换了xray的lic）：

![截屏2022-01-26 上午11 06 21](https://user-images.githubusercontent.com/54735907/151097395-8d769267-f563-4b87-849a-7edc45408dec.png)
![截屏2022-01-26 上午11 09 28](https://user-images.githubusercontent.com/54735907/151097604-b402e819-3b19-4811-bcae-fc9f7f1c5174.png)
<img width="422" alt="截屏2022-01-26 上午11 07 43" src="https://user-images.githubusercontent.com/54735907/151097491-690b4e4f-b21a-49f6-b0e5-1098bf127229.png">

**Comment by 1in9e** [comment]
扫描过程，可见flower；
另外，也可以从日志看看各个模块的运行情况：
gosint/logs/
gosint/client/logs/
