### ISSUE TITLE
rescan() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by zjhzjhhh** [1in9e/gosint#28]
师傅你好，在添加扫描任务后会出现这个错误rescan() takes 1 positional argument but 3 were given
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/64487620/204981035-0773281e-300d-45ad-a0b1-eba33a22e3fa.png">

**Comment by 1in9e** [comment]
你好，你应该是点了「测试按钮」，这个目前没有绑定具体功能，添加任务直接增加即可。
