### ISSUE TITLE
gosint_client 一直在重启

### ISSUE THREAD

**Issue by wycdavid** [1in9e/gosint#3]
gosint_client 一直在重启可能是什么原因，还有，日志和celery监控都打不开，哪里可以看到输出的日志？

**Comment by gdft2112** [comment]
也许这就是为什么我添加好了没跑出东西的原因😂

**Comment by wycdavid** [comment]
> 也许这就是为什么我添加好了没跑出东西的原因😂

我很顺利的安装好了，也没有报错，该配置的也配置了。。但是一直在扫描中，然后我就看下docker的状态，发现client一直重启中，几秒钟就重启一次，应该是报错了，但是我不知道怎么看日志。。。

**Comment by wycdavid** [comment]
> 也许这就是为什么我添加好了没跑出东西的原因😂

我直接看了docker的日志，应该是xray的问题
/docker-entrypoint.sh: line 78: /app/logs/xray.log: No such file or directory

**Comment by wycdavid** [comment]
不过，我把跟xray相关的功能都关闭了，也没这个报错了，但是还是不断的重启。。

**Comment by gdft2112** [comment]
那我不知道了。。

**Comment by gdft2112** [comment]
工具很好就是跑不起来很尴尬😩😩😩

**Comment by L0ading-x** [comment]
我的也是一直在重启

**Comment by ad-calcium** [comment]
我也在重启

**Comment by 1in9e** [comment]
感谢反馈～
客户端重启为logs日志目录未能成功创建的原因，可先在clinet下手动创建logs目录，然后再启docker-compose即可解决；celery监控默认未开启，下个版本更新
