### ISSUE TITLE
README.md 没有账号密码

### ISSUE THREAD

**Issue by Liang2580** [1in9e/gosint#4]
Docker启动之后没有写明账号  gosint 密码gosint

全靠猜了

**Comment by Liang2580** [comment]
建议在启动docker 哪里写明清楚。账号密码。

**Comment by gdft2112** [comment]
账号密码在docker-entrypoint.sh文件里面修改就行了，有python manage.py shell的那个，分别是账号 邮箱和密码，不过二次启动要改下用户名，不然会报错

**Comment by 1in9e** [comment]
感谢反馈～
下个版本更新
