### ISSUE TITLE
Docker 版本扫描直接500

### ISSUE THREAD

**Issue by Liang2580** [1in9e/gosint#5]
![0c204aeec2ee101199c2cfff917e68c](https://user-images.githubusercontent.com/27684409/147453945-3d6d695c-767f-4183-8ba0-0bbe6f52286c.png)

**Comment by Liang2580** [comment]
没有添加项目名称。直接报错500 了。

**Comment by Liang2580** [comment]
以为不能用呢。！！！

**Comment by gdft2112** [comment]
你没换密码换全，你可以grep gosint看看哪里有gosintpass,我也是一个问题解决了

**Comment by 1in9e** [comment]
项目名称为必填项，感谢反馈～
